config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { confirmations: 'confirmations',
                                    omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post 'confirm_email', to: 'omniauth_callbacks#confirm_email'
    authenticate :user do
      get 'profile', to: 'omniauth_callbacks#profile' # , as: :authenticated_root
    end
  end

  root 'questions#index'

  get '/search', to: 'search#show'

  get 'users/:id' => 'users#show', as: :user

  concern :voting do
    post :good, :shit, :revoke, on: :member
  end

  resources :questions, concerns: [:voting] do
    post :subscribe, :unsubscribe, on: :member
    resources :comments, only: [:new, :create], defaults: { commentable: 'questions' }
    resources :answers, concerns: [:voting], shallow: true, except: :show do
      resources :comments, only: [:new, :create], defaults: { commentable: 'answers' }
      post :solution, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :questions do
        resources :answers, shallow: true
      end
      resources :profiles do
        get :me, on: :collection
      end
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Commentable
  include Votable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_one :solution, -> { where best: true }, class_name: 'Answer'
  has_many :attachments, as: :attachable
  has_many :subscriptions, dependent: :destroy

  validates :title, :body, :user, presence: true
  validates :title, presence: true, length: { in: 4..69 }
  validates :body, presence: true, length: { in: 10..512 }
  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  scope :daily, -> { where('created_at > ?', 1.day.ago) }

  after_create :subscribe_author

  def subscribe(user)
    subscriptions.find_or_create_by(user: user)
  end

  def unsubscribe(user)
    sub = subscriptions.find_by(user: user)
    sub.destroy if sub
  end

  private

  def subscribe_author
    subscribe user
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: [:show, :answers]

  def index
    authorize Question
    respond_with Question.all
  end

  def show
    respond_with @question
  end

  def answers
    # render nothing: true, status: :success
    respond_with @question.answers
  end

  def create
    authorize @question = current_user.questions.create(question_params)
    respond_with( @question )
    PrivatePub.publish_to '/questions', question: @question.to_json if @question.valid?
  end

  private

  def load_question
    @question = Question.find(params[:id])
    authorize @question
    # skip_authorization
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, except: [:index, :new, :create]

  include Voting

  def index
    respond_with( @questions = Question.all )
  end

  def show
    respond_with @question
  end

  def subscribe
    @question.subscribe current_user
    render 'subscription'
  end

  def unsubscribe
    @question.unsubscribe current_user
    render 'subscription'
  end

  def new
    @question = current_user.questions.build
    authorize Question
    respond_with( @question )
  end

  def edit
  end

  def create
    @question = current_user.questions.create(question_params)
    authorize @question
    respond_with( @question )
    PrivatePub.publish_to '/questions', question: @question.to_json if @question.valid?
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with @question.destroy
  end

  private

  def question_params
    params.require(:question).permit(:title, :body,
                                     attachments_attributes: [:id, :file, :_destroy])
  end

  def load_question
    @question = Question.find params[:id]
    authorize @question
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def subscription_link(question)
    if policy(question).subscribe?
      link_to 'subscribe', subscribe_question_path(question),
              method: :post, remote: true, class: 'btn btn-warning btn-xs'
    else
      link_to 'unsubscribe', unsubscribe_question_path(question),
              method: :post, remote: true, class: 'btn btn-danger btn-xs'
    end
  end

  def question_cache_key(question)
    own = "#{policy(question).owner?}"
    "question-#{question.id}-#{own}-#{question.updated_at.to_i}"
  end
end

app/views/questions/_form.html.slim
= bootstrap_form_for @question do |f|

  = f.text_field :title, label: "Your question", autofocus:true
  = f.text_area :body, label: "more details"

  .attachments
    = link_to_add_association 'add attachment', f, :attachments,
        :data => {"association-insertion-method" => "append" },
         partial: 'shared/attachment_fields', class: 'btn btn-link'

  = f.fields_for :attachments, layout: :inline do |att|
    = att.check_box :_destroy, label: att.object.title

  = f.submit 'save question', class: 'btn btn-success btn-sm'
  - unless @question.new_record?
    = '  |  '
    = link_to 'Back to question', question_path(@question), class: 'btn btn-primary btn-sm'

app/views/questions/_question.html.slim
.question id= "question_#{@question.id}" data={question_id: "#{@question.id}", author: "#{policy(@question).owner?}"}
  .row
    = render 'voting'
    .col-md-7
      .subscription= subscription_link @question if signed_in?
      - cache question_cache_key(@question) do
        h3= @question.title
        - if policy(@question).owner?
          = link_to 'edit', edit_question_path(@question), class: 'btn btn-warning btn-xs'
          = link_to 'delete', @question, method: :delete, class: 'btn btn-danger btn-xs'
        p
          = @question.body
          - @question.attachments.each do |att|
            ul
              li= link_to att.file.identifier, att.file.url, class: "btn btn-link"
        .comments id= div_comments_id(@question)
          - @question.comments.each do |comment|
            - cache comment do
              p= comment.body
          = comment_link @question if policy(Comment).create?

app/views/questions/_voting.html.slim
- cache voting_cache_key(@question) do
  .col-md-2
    br
    vote.text-center
      = link_to 'good!', good_question_path(@question),
        method: :post,
        remote: true,
        data: { type: :json },
        class: "btn btn-success btn-xs #{ 'disabled' unless policy(@question).good? }", id: "good_question_#{@question.id}"
      br
      strong id= "rating_question_#{@question.id}"
        = @question.rating
      = link_to 'revoke', revoke_question_path(@question),
          method: :post,
          remote: true,
          data: { type: :json },
          class: "btn btn-link #{ 'disabled' unless policy(@question).revoke? }", id: "revoke_question_#{@question.id}"
      br
      = link_to 'shit!', shit_question_path(@question),
        method: :post,
        remote: true,
        data: { type: :json },
        class: "btn btn-success btn-xs #{ 'disabled' unless policy(@question).shit? }", id: "shit_question_#{@question.id}"

app/views/questions/edit.html.slim
  h3 Edit a question
  br
  = render 'form'

app/views/questions/index.html.slim
- cache collection_cache_key_for :question do
  br
  table class="table table-hover" id='questions'
    - @questions.each do |question|
      tr
        td = link_to question.title, question_path(question)
        td = question.body

- if policy(Question).new?
  = link_to 'Ask a Question', new_question_path, class: 'btn btn-primary'

= subscribe_to "/questions"

app/views/questions/new.html.slim
= render 'form'
br
= link_to 'Browse all questions', questions_path, class: 'btn btn-primary btn-sm'

app/views/questions/show.html.slim
= render 'question'
.answers
  = render 'answers/list', question: @question

- if signed_in?
  = render 'answers/form', question: @question, answer: nil

= subscribe_to "/question/#{@question.id}/answers"
= subscribe_to "/question/#{@question.id}/comments"

app/views/questions/subscription.js.erb
$('.subscription').html('<%= escape_javascript subscription_link @question %>');