config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { confirmations: 'confirmations',
                                    omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post 'confirm_email', to: 'omniauth_callbacks#confirm_email'
    authenticate :user do
      get 'profile', to: 'omniauth_callbacks#profile' # , as: :authenticated_root
    end
  end

  root 'questions#index'

  get '/search', to: 'search#show'

  get 'users/:id' => 'users#show', as: :user

  concern :voting do
    post :good, :shit, :revoke, on: :member
  end

  resources :questions, concerns: [:voting] do
    post :subscribe, :unsubscribe, on: :member
    resources :comments, only: [:new, :create], defaults: { commentable: 'questions' }
    resources :answers, concerns: [:voting], shallow: true, except: :show do
      resources :comments, only: [:new, :create], defaults: { commentable: 'answers' }
      post :solution, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :questions do
        resources :answers, shallow: true
      end
      resources :profiles do
        get :me, on: :collection
      end
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Commentable
  include Votable

  belongs_to :question, touch: true
  belongs_to :user
  has_many :attachments, as: :attachable
  validates :body, presence: true, length: { in: 17..512 }
  validates :question, :user, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  scope :best, -> { where(best: true) }
  scope :solution_first, -> { order(best: :desc) }

  after_create :alert_subscribers

  def set_solution
    transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end

  private

  def alert_subscribers
    NewAnswerJob.perform_later question
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: :create
  before_action :load_answer, only: [:edit, :update, :destroy, :solution]

  respond_to :js
  include Voting

  def create
    @answer = @question.answers.create( answer_params.merge( user: current_user ))
    authorize @answer
  end

  def edit
  end

  def update
    @answer.update(answer_params)
    respond_with @answer
  end

  def destroy
    @question = @answer.question
    respond_with @answer.destroy
  end

  def solution
    @answer.set_solution
    respond_with @answer
  end

  private

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
  end

  def load_question
    @question = Question.find params[:question_id]
  end

  def load_answer
    @answer = Answer.find params[:id]
    authorize @answer
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: :create

  def index
    authorize Answer
    respond_with Answer.all
  end

  def create
    @answer = @question.answers.create( answer_params.merge( user: current_user ))
    authorize @answer
    respond_with @answer
    publish_answer
  end

  def show
    authorize @answer = Answer.find(params[:id])
    respond_with @answer
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def load_question
    @question = Question.find params[:question_id]
  end

  def publish_answer
    PrivatePub.publish_to "/question/#{@question.id}/answers", answer: {
      id: @answer.id, body: @answer.body,
      attachments: @answer.attachments.map { |att| { name: att.identifier, url: att.url } }
    }.to_json if @answer.valid?
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
p id= "answer_#{answer.id}"
  = link_to 'Mark as Solution', solution_answer_path(answer), method: :post, remote: true, class: 'btn btn-success btn-xs' if policy(answer).solution?
  = render 'answers/answer_voting', answer: answer
  = render 'answers/edit_delete_buttons', answer: answer
  = answer.body
  attachments id= "attachments_answer_#{answer.id}"
    - answer.attachments.each do |att|
      = link_to att.file.identifier, att.file.url, class: "btn btn-link"
  = answer.body
  .row
    .comments.col-md-5.col-md-offset-1 id= div_comments_id(answer)
      - cache answer do
        - answer.comments.each do |comment|
          p= comment.body unless comment.new_record?

app/views/answers/_answer_lite.html.slim
p id= "answer_#{answer.id}"
  = answer.body
  attachments id= "attachments_answer_#{answer.id}"
    - answer.attachments.each do |att|
      = link_to att.file.identifier, att.file.url, class: "btn btn-link"
  .row
    .comments.col-md-5.col-md-offset-1 id= div_comments_id(answer)

app/views/answers/_answer_voting.html.slim
vote id= "vote_answer_#{answer.id}"
  = link_to '+', good_answer_path(answer),
  method: :post,
  remote: true,
  data:{type: :json },
  class: "btn btn-link #{ 'disabled' unless policy(answer).good? }",
          id: "good_answer_#{answer.id}"
  = '/'
  = link_to '-', shit_answer_path(answer),
    method: :post,
    remote: true,
    data:{type: :json },
    class: "btn btn-link #{ 'disabled' unless policy(answer).shit? }",
            id: "shit_answer_#{answer.id}"
  strong id= "rating_answer_#{answer.id}"
    = answer.rating
  = link_to 'X', revoke_answer_path(answer),
    method: :post,
    remote: true,
    data:{ type: :json },
    class: "btn btn-link #{ 'disabled' unless policy(answer).revoke? }",
            id: "revoke_answer_#{answer.id}"
  = comment_link answer if policy(Comment).create?

app/views/answers/_edit_delete_buttons.html.slim
= link_to 'edit', edit_answer_path(answer), remote: true, class: 'btn btn-link' if policy(answer).edit?
'
= link_to 'delete', answer_path(answer), remote: true, method: :delete, class: 'btn btn-link' if policy(answer).destroy?
'

app/views/answers/_edit_form.html.slim
= bootstrap_form_for @answer, remote: true do |f|
  = f.text_area :body, label: 'Edit Answer'
  .attachments
    = link_to_add_association 'add attachment', f, :attachments,
        :data => {"association-insertion-method" => "append" },
         partial: 'shared/attachment_fields', class: 'btn btn-link'

  = f.fields_for :attachments, layout: :inline do |att|
    = att.check_box :_destroy, label: att.object.title

  = f.submit 'Save Answer', class: 'btn btn-success btn-sm'

app/views/answers/_form.html.slim
= bootstrap_form_for [ question, answer || question.answers.build ], remote: true do |f|
  = f.text_area :body, label: 'Type your answer', autofocus: true
  .attachments
    = link_to_add_association 'add attachment', f, :attachments,
        :data => {"association-insertion-method" => "append" },
         partial: 'shared/attachment_fields', class: 'btn btn-link'
    = f.fields_for :attachments, layout: :inline do |att|
  = f.submit 'Add an answer', class: 'btn btn-success btn-sm', align: 'right'

app/views/answers/_list.html.slim
h2 Answers:
- question.answers.includes(:comments, :attachments, :votes).solution_first.each do |answer|
  br
  - if answer.persisted?
    = render 'answers/answer', answer: answer

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  $('.alert').html('');
  <% if remotipart_submitted? %>
    $('.new_answer').html('<%= j "#{render 'form, question: @question, answer: @answer'}" %>');
  <% else %>
    $('.new_answer').html('<%= j render 'form', question: @question, answer: @answer %>');
  <% end %>
<% else %>
  $('.alert').html('<div class="alert alert-success">Your answer successfully created.</div>');
  $('.answers').append('<%= escape_javascript render 'answer',answer: @answer %>');
  $('.new_answer').html('<%= j render 'form', question: @question, answer: nil %>');
  var ansHtml = '<%= j render 'answer',answer: @answer %>';
  if ($.exists('#answer_<%= @answer.id %>')) {
   $('#answer_<%= @answer.id %>').replaceWith( ansHtml);
   console.log('exist for author');
                                } else {
   $('.answers').append( ansHtml);
   console.log('not exist for author');
                                        };
  <% publish_to "/question/#{@answer.question_id}/answers" do %>
    if ($.exists('#answer_<%= @answer.id %>')) {
     $('.alert').html('<div class="alert alert-success">Answer already exists.</div>');
     console.log('exist for others');
                                  } else {
     $('.answers').append('<%= j render 'answer_lite',answer: @answer %>');
     console.log('not exist for others');
                                          };
  <% end %>
<% end %>

app/views/answers/destroy.js.erb
$('#answer_<%= @answer.id %>').html('<div class="alert alert-success">Answer destroyed successfully!</div>');

app/views/answers/edit.js.erb
$('#answer_<%= @answer.id %>').html('<%= escape_javascript render 'edit_form' %>');

app/views/answers/solution.js.erb
$('.answers').html('<%= escape_javascript render 'answers/list', question: @answer.question %>');
$('.alert').html('<div class="alert alert-success">The best answer is chosen!</div>');

app/views/answers/update.js.erb
$('#answer_<%= @answer.id %>').replaceWith('<%= escape_javascript render 'answer',answer: @answer %>');
$('.alert').html('<div class="alert alert-success">Answer edited successfully!</div>');